### PR TITLE
Fix race conditions in URCOMLoader

### PR DESCRIPTION
**Pull request by babgvant**

### CODE REVIEW

**Comment by babgvant** [comment]
There are a couple TODOs, the most critical is that I need to know the best way to throw a dialog at the user.

**Comment by LukePulverenti** [comment]
should we just bundle the com objects with the app so that there's always something available? then the app can just upgrade.

**Comment by babgvant** [comment]
We can, just have to include the date files so they don't get overwritten
unnecessarily.

**Comment by LukePulverenti** [comment]
can you make that change? that will allow us to get rid of the 60000 load wait and not require any visible error message. i suppose you can just add the zip as an embedded resource, then you can probably extract and feed into the same code. so the new workflow would be:

if files exists -> check upgrade
else -> extract from embedded

**Comment by babgvant** [comment]
Those would still need to be there.

The 60000 potential wait only happens if the URCOMLoader is updating the
COM objects, otherwise it won't block (this solves the race that can happen
if the filters have changed and the user opens the app and tries to play
something before they can finish updating). Ideally, the load would detect
that it is waiting and signal via so UI that something is happening so the
user doesn't think the UI locked (i.e. a spinner), but I don't know if that
functionality exists in the app currently.

If the objects have been loaded (by playing something) it's not possible to
unload/replace/recover because of how the custom EVR Presenter overlays the
EVR (it will crash because the pointer will move if you try it). So if you
switch tracks after playing something the URCOMLoader will signal that a
refresh should happen in the next app load (by deleting the tracking
files), but ideally would tell the user that the switch won't really happen
until MBT is restarted. I don't expect that users will switch
back-and-forth that often so it shouldn't be a huge UX issue.

I'll have a look at embedding the zips tomorrow.

**Comment by babgvant** [comment]
Zips are now part of the assembly.

**Comment by LukePulverenti** [comment]
Quick question - when you say URLComLoader is updating the COM objects...do you mean download in progress, or download completed but registering the objects?

**Comment by babgvant** [comment]
Downloading and replacing the dlls on the filesystem.

**Comment by LukePulverenti** [comment]
Thanks. In order to avoid that potential 60000ms wait, can they be downloaded to a temp directory, then quickly moved to their final destinations all in one shot? Then the UI will never have to lock on the downloading operation, just only the file transfer.

**Comment by babgvant** [comment]
They can't be replaced after being loaded or MBT may crash (unfortunate artifact of how the EVR presenter overlays the EVR). It would be possible to DL to temp dir and overwrite on close or next open, but it would still need to block to make sure that the transaction completed. The 60s is just an arbitrary # (the max I've found that people will wait before questioning whether they should just kill a process). I'd rather have the load method work something like:

if get object short wait (like 100ms)
else
    display long running we're updating the filters process UI
    wait max time (something longer than 60s) to load

But I don't know if the long running UI exists, or if it does how to trigger it. Either way, the 60s is a worst case scenario that can only happen if the filters need to be updated (which doesn't happen that often). If they don't need updating it won't block. 

I also just added a PING check to ensure that the CDN is accessible before blocking.

**Pull request merged**
